language: java
sudo: false
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install: ./gradlew wrapper
before_script:
  - wget http://services.gradle.org/distributions/gradle-3.1-bin.zip
  - unzip gradle-3.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.1
  - export PATH=$GRADLE_HOME/bin:$PATH