main: cloud.swiftnode.kvaccine.KVaccine
name: K-Vaccine
version: @version@
author: EntryPoint
commands:
  kvc:
    description: KVaccine main command.
    usage: /kvc (force|info|check|debug|firstkick|remove)
